[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas==2.2.0",
    "plotly==5.18.0",
    "streamlit==1.32.0",
]
